// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        pgtype.UUID        `db:"id"`
	ClientID  int64              `db:"client_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	Status    string             `db:"status"`
}

type OrderItem struct {
	OrderID   pgtype.UUID `db:"order_id"`
	ProductID pgtype.UUID `db:"product_id"`
	Quantity  int32       `db:"quantity"`
}

type PromotionRegistration struct {
	ID        pgtype.UUID        `db:"id"`
	ClientID  int64              `db:"client_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	Email     string             `db:"email"`
}
