// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	Count(ctx context.Context) (int64, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
}

var _ Querier = (*Queries)(nil)
