package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"math/rand/v2"
	"os"
	"os/signal"
	"syscall"

	"github.com/joho/godotenv"
	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

type Order struct {
	Id       string `json:"id"`
	Products []struct {
		Id     string `json:"id"`
		Name   string `json:"name"`
		Amount int    `json:"amount"`
	} `json:"products"`
}

const (
	routingKeyApproved = "pagamento.aprovado"
	routingKeyDeclined = "pagamento.recusado"
)

var bindingKeys = []string{"pedido.estoque_ok"}

func main() {
	if err := run(); err != nil {
		slog.Error("fatal", "error", err)
		os.Exit(1)
	}
}

func run() error {
	// Create a context that will be canceled on SIGINT (Ctrl+C) or SIGTERM.
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	if err := godotenv.Load(); err != nil {
		slog.Warn("no .env file found, using environment variables")
	}

	settings, err := LoadSettings()
	if err != nil {
		return fmt.Errorf("Failed to load settings: %v", err)
	}

	SetupLogger(settings.LogLevel)

	env := rmq.NewEnvironment(settings.BrokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		return fmt.Errorf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	_, err = conn.Management().DeclareExchange(ctx, &rmq.DirectExchangeSpecification{Name: settings.ExchangeName})
	if err != nil {
		return fmt.Errorf("Failed to declare an exchange: %v", err)
	}

	publisher, err := conn.NewPublisher(ctx, nil, nil)
	if err != nil {
		return fmt.Errorf("Failed to create publisher: %v", err)
	}
	defer func() { _ = publisher.Close(context.Background()) }()

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		return fmt.Errorf("Failed to declare a queue: %v", err)
	}

	for _, bk := range bindingKeys {
		_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   settings.ExchangeName,
			DestinationQueue: qInfo.Name(),
			BindingKey:       bk,
		})
		if err != nil {
			return fmt.Errorf("Failed to bind a queue: %v", err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), &rmq.ConsumerOptions{
		InitialCredits: 1, // One message at a time
	})
	if err != nil {
		return fmt.Errorf("Failed to create consumer: %v", err)
	}
	defer func() { _ = consumer.Close(context.Background()) }()

	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				slog.Info("Shutting down gracefully...")
				return nil
			}
			return fmt.Errorf("Failed to receive a message: %v", err)
		}

		message := delivery.Message()

		var order Order
		err = json.Unmarshal(message.Data[0], &order)
		if err != nil {
			slog.Error("Failed to unmarshal message", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		slog.Info("Iniciando pagamento", "order", order)

		randomInt := rand.IntN(100)
		shouldAprove := randomInt < 80 // 80% chance of approval

		var routingKey string
		if shouldAprove {
			slog.Info("Pagamento aprovado", "order", order)
			routingKey = routingKeyApproved
		} else {
			slog.Info("Pagamento recusado", "order", order)
			routingKey = routingKeyDeclined
		}

		payload, err := json.Marshal(order)
		if err != nil {
			slog.Error("Failed to marshal order", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		event, err := rmq.NewMessageWithAddress([]byte(payload), &rmq.ExchangeAddress{
			Exchange: settings.ExchangeName,
			Key:      routingKey,
		})
		if err != nil {
			slog.Error("Failed to create message", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		res, err := publisher.Publish(ctx, event)
		if err != nil {
			slog.Error("Failed to publish", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		switch res.Outcome.(type) {
		case *rmq.StateAccepted:
		case *rmq.StateRejected:
			slog.Error("Message was rejected", "outcome", res.Outcome)
			_ = delivery.Discard(ctx, nil)
			continue
		case *rmq.StateReleased:
			slog.Info("Message was released", "outcome", res.Outcome)
			_ = delivery.Discard(ctx, nil)
			continue
		case *rmq.StateModified:
			slog.Error("Message was modified", "outcome", res.Outcome)
			_ = delivery.Discard(ctx, nil)
			continue
		default:
			slog.Error("Unexpected publish outcome", "outcome", res.Outcome)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		err = delivery.Accept(ctx)
		if err != nil {
			slog.Error("Failed to accept message", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}
	}
}
