package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

type Broker struct {
	env          *rmq.Environment
	publisher    *rmq.Publisher
	consumer     *rmq.Consumer
	exchangeName string
}

func NewBroker(ctx context.Context, uri, exchangeName string, bindingKeys []string) (*Broker, error) {
	env := rmq.NewEnvironment(uri, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		return nil, fmt.Errorf("Failed to connect to RabbitMQ: %v", err)
	}

	_, err = conn.Management().DeclareExchange(ctx, &rmq.DirectExchangeSpecification{Name: exchangeName})
	if err != nil {
		return nil, fmt.Errorf("Failed to declare an exchange: %v", err)
	}

	publisher, err := conn.NewPublisher(ctx, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("Failed to create publisher: %v", err)
	}

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to declare a queue: %v", err)
	}

	for _, bk := range bindingKeys {
		_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   exchangeName,
			DestinationQueue: qInfo.Name(),
			BindingKey:       bk,
		})
		if err != nil {
			return nil, fmt.Errorf("Failed to bind a queue: %v", err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), &rmq.ConsumerOptions{
		InitialCredits: 1, // One message at a time
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to create consumer: %v", err)
	}

	return &Broker{
		env:          env,
		publisher:    publisher,
		consumer:     consumer,
		exchangeName: exchangeName,
	}, nil
}

func (b *Broker) Close() error {
	return errors.Join(
		b.env.CloseConnections(context.Background()),
		b.publisher.Close(context.Background()),
		b.consumer.Close(context.Background()),
	)
}

func (b *Broker) Publish(ctx context.Context, routingKey string, message []byte) error {
	event, err := rmq.NewMessageWithAddress(message, &rmq.ExchangeAddress{
		Exchange: b.exchangeName,
		Key:      routingKey,
	})
	if err != nil {
		return fmt.Errorf("Failed to create message: %v", err)
	}

	res, err := b.publisher.Publish(ctx, event)
	if err != nil {
		return fmt.Errorf("Failed to publish message: %v", err)
	}

	switch res.Outcome.(type) {
	case *rmq.StateAccepted:
		slog.Debug("Message was accepted")
		return nil
	case *rmq.StateReleased:
		return fmt.Errorf("Message was released %v", res.Outcome)
	case *rmq.StateRejected:
		return fmt.Errorf("Message was rejected: %v", res.Outcome)
	case *rmq.StateModified:
		return fmt.Errorf("Message was modified: %v", res.Outcome)
	default:
		return fmt.Errorf("Unexpected publish outcome: %v", res.Outcome)
	}
}

func (b *Broker) Consume(ctx context.Context, handler func(context.Context, rmq.IDeliveryContext) error) error {
	for {
		delivery, err := b.consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				slog.Info("Shutting down gracefully...")
				return nil
			}
			return fmt.Errorf("Failed to receive a message: %v", err)
		}

		if err := handler(ctx, delivery); err != nil {
			slog.Error("Error handling message", "error", err)
			_ = delivery.Discard(ctx, nil)
		}
	}
}
