package rabbitmq

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/url"
	"promotions/internal/signing"
	"strings"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

type Consumer[T any] struct {
	consumer *rmq.Consumer
	signer   *signing.Signer
}

func NewConsumer[T any](ctx context.Context, signer *signing.Signer, conn *rmq.AmqpConnection, exchangeName, routingKey string) (*Consumer[T], error) {
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to declare a queue: %v", err)
	}

	_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
		SourceExchange:   exchangeName,
		DestinationQueue: qInfo.Name(),
		BindingKey:       routingKey,
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to bind a queue: %v", err)
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), &rmq.ConsumerOptions{
		InitialCredits: 1, // One message at a time
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to create consumer: %v", err)
	}

	return &Consumer[T]{
		consumer: consumer,
		signer:   signer,
	}, nil
}

func (c *Consumer[T]) Run(ctx context.Context, handler func(context.Context, T) error) {
	for {
		delivery, err := c.consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				slog.Info("Shutting down gracefully...")
				return
			}
			slog.Error("Failed to receive a message", "error", err)
			return
		}

		message := delivery.Message()

		if len(message.Data) == 0 {
			slog.Error("Received message with no data")
			_ = delivery.Discard(ctx, nil)
			continue
		}

		if len(message.Data) > 1 {
			slog.Error("Received message with multiple data parts")
			_ = delivery.Discard(ctx, nil)
			continue
		}

		if len(message.Data[0]) == 0 {
			slog.Error("Received message with empty data")
			_ = delivery.Discard(ctx, nil)
			continue
		}

		from, ok := message.ApplicationProperties["from"].(string)
		if !ok {
			slog.Error("Received message with no 'from' property")
			_ = delivery.Discard(ctx, nil)
			continue
		}

		sig, ok := message.ApplicationProperties["signature"].(string)
		if !ok {
			slog.Error("Received message with no signature")
			_ = delivery.Discard(ctx, nil)
			continue
		}
		data := message.Data[0]

		err = c.signer.Verify(from, sig, data)
		if err != nil {
			slog.Error("Received message with invalid signature", "error", err)
			_ = delivery.Discard(ctx, nil)
			continue
		}

		var to, subject *string
		if message.Properties != nil {
			to = message.Properties.To
			subject = message.Properties.Subject
		}

		routingKey := routingKeyOf(to, subject)

		slog.Debug("Received message", "from", from, "routingKey", routingKey)

		var event T
		err = json.Unmarshal(data, &event)
		if err != nil {
			slog.Error("Failed to unmarshal message", "error", err)
			continue
		}

		err = handler(ctx, event)
		if err != nil {
			slog.Error("Failed to handle event", "error", err)
		}
	}
}

func routingKeyFromAddress(address string) string {
	const prefix = "/exchanges/"

	if !strings.HasPrefix(address, prefix) {
		return ""
	}

	rest := address[len(prefix):]

	_, after, ok := strings.Cut(rest, "/")
	if !ok {
		return ""
	}

	encodedKey := after
	if encodedKey == "" {
		return ""
	}

	key, err := url.PathUnescape(encodedKey)
	if err != nil {
		slog.Warn("Failed to decode routing key", "address", address, "error", err)
		return encodedKey
	}

	return key
}

func routingKeyOf(to, subject *string) string {
	if to != nil {
		if key := routingKeyFromAddress(*to); key != "" {
			return key
		}
	}

	if subject != nil {
		return *subject
	}

	return ""
}
